using System;
using System.Collections.Generic;

namespace Utilities
{
    [Serializable]
    public class SubBatch   // sent from global coordinator to local coordinator
    {
        public readonly long bid;
        public readonly Guid coordID;

        public long lastBid;
        public List<long> txnList;

        public long highestCommittedBid;

        // NOTICE: this field is only used for batches generated by local coordinators
        public long lastGlobalBid;

        public SubBatch(long bid, Guid coordID)
        {
            lastBid = -1;
            this.bid = bid;
            this.coordID = coordID;
            txnList = new List<long>();
            lastGlobalBid = -1;
            highestCommittedBid = -1;
        }

        public SubBatch(SubBatch subBatch)
        {
            bid = subBatch.bid;
            coordID = subBatch.coordID;
            lastBid = subBatch.lastBid;
            txnList = subBatch.txnList;
            lastGlobalBid = subBatch.lastGlobalBid;
        }
    }

    [Serializable]
    public class LocalSubBatch : SubBatch     // sent from local coordinator to transactional grains
    {
        public readonly long globalBid;
        public Dictionary<long, long> globalTidToLocalTid;

        public long highestCommittedGlobalBid;

        public LocalSubBatch(long globalBid, SubBatch subBatch) : base(subBatch)
        {
            this.globalBid = globalBid;
            globalTidToLocalTid = new Dictionary<long, long>();
            highestCommittedGlobalBid = -1;
        }
    }
}